config/routes.rb
Rails.application.routes.draw do
  root "admin/products#index"
  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
    }
  namespace :admin do 
    resources :products do 
      get '/page/:page', action: :index, on: :collection
    end
    get "orders/:status", to: "orders#index", as: :orders
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 5
  belongs_to :category
  has_one_attached :main_picture 
  has_many_attached :pictures 
  has_many :order_details 
  has_many :orders, through: :order_details
  validates :name, :price, :description, :brand, :category_id, :weight, presence: true

  validates :price, :weight, numericality: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    layout "admin"
    before_action :authenticate_user!
    before_action :authenticate_admin_user?
    before_action :set_product, only: %i[ show edit update destroy ]
  
    def index
      @products = Product.page params[:page]
    end
  

    def show
    end
  

    def new
      @product = Product.new
      @categories = Category.all
    end
  

    def edit 
      @categories = Category.all
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path, notice: "Product was successfully created." 
      else
        @categories = Category.all
        render :new, status: :unprocessable_entity 
      end
    end

    def update
        if @product.update(product_params)
          redirect_to admin_products_path, notice: "Product was successfully updated."
        else
          @categories = Category.all  
          render :edit, status: :unprocessable_entity 
        end
    end
  
    def destroy
      @product.destroy
         redirect_to admin_products_path, notice: "Product was successfully destroyed."
    end
  
    private
      def set_product
        @product = Product.find(params[:id])
      end

      def product_params
        params.require(:product).permit(:name, :price, :description, :brand, :category_id, :weight, :main_picture, pictures: [], )
      end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
<h1>Edit Product</h1>

<%=  form_with(url:  admin_product_path(@product), model: @product, method: :patch ) do |form| %>

    <div class="row">  
      <div class="col-4">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
        </div>
    </div>
<br>

    <div class="row">  
      <div class="col-4">
        <%= form.label :brand %>
        <%= form.text_field :brand, class: "form-control" %>
        </div>
    </div>  
<br>

<div class="row">  
      <div class="col-4">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
        </div>
    </div>
<br>
    
    <div class="row">  
      <div class="col-4">
        <%= form.label :price %>
        <%= form.number_field :price,  class: "form-control" %>
    </div>
    </div>
<br>
    
    <div class="row">  
      <div class="col-4">
        <%= form.label :weight %>
        <%= form.number_field :weight,  class: "form-control" %>
    </div>
    </div>
<br>
    <div class="row">  
      <div class="col-4">
        <%= form.label :main_picture %>
        <%= form.file_field :main_picture, class: "form-control" %>
    </div>
    </div>
<br>
    <div class="row">  
      <div class="col-4">
        <%= form.label :pictures %>
        <%= form.file_field :pictures, class: "form-control", multiple: true %>
    </div>
    </div>
<br>

    <div class="row">  
      <div class="col-4">
        <%= form.label :category %>
        
        <% options = options_from_collection_for_select(@categories, 'id', 'name') %>
        <%= form.select :category_id, options,  class: "form-control btn btn-secondary dropdown-toggle" %>
        </div>
    </div>
    <br>
    <%= form.submit class: "btn btn-primary " %>
<% end %>
<div>

app/views/admin/products/index.html.erb
<div class="title text-center">
<div>
  <%= link_to "New Product", new_admin_product_path %>
</div> 
<br>
  <h1>Product List</h1>
</div>
<table class="table table-striped  text-center">
  <thead>
    <th scope="col">ID</th> 
    <th scope="col">Product Name</th>
    <th scope="col">description</th>
    <th scope="col">Price</th>
    <th scope="col">Brand</th>
    <th scope="col">Category</th>
    <th scope="col">Weight</th>
  </thead>

  <tbody>
    <% for product in @products %> 
      <tr>
        <td><%= product.id %> </td>
        <td><%= product.name %> </td>
        <td><%= product.description %> </td>
        <td><%= product.price %> </td>
        <td><%= product.brand %> </td>
        <td><%= product.category.name %> </td>
        <td><%= product.weight %> </td>
          <td>
          <div>
            <%= link_to "View", admin_product_path(product) %>
          </div>
        </td>
        <td>
          <div>
            <%= link_to "Edit", edit_admin_product_path(product) %>
          </div>
        </td>

        <td>
          <div>
          <%= link_to "Delete", admin_product_path(product), class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Do you want to delete product ?" }%>
          </div>
        </td>
      </tr>
    <% end %>
  <tbody>
</table> 
<div>
<%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<div class="container">
<h1>New Product</h1>
  <%= render "devise/shared/error_messages", resource: @product %>

<%=  form_with(url:  admin_products_path, model: @product, method: :post ) do |form| %>

    <div class="row">  
      <div class="col-4">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", required: true %>
        </div>
    </div>
<br>

    <div class="row">  
      <div class="col-4">
        <%= form.label :brand %>
        <%= form.text_field :brand, class: "form-control", required: true %>
        </div>
    </div>  
<br>

<div class="row">  
      <div class="col-4">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control", required: true %>
        </div>
    </div>
<br>
    
    <div class="row">  
      <div class="col-4">
        <%= form.label :price %>
        <%= form.number_field :price,  class: "form-control", required: true, pattern: "[0-9]*"%>
    </div>
    </div>
<br>
    
    <div class="row">  
      <div class="col-4">
        <%= form.label :weight %>
        <%= form.number_field :weight,  class: "form-control", required: true,  pattern: "[0-9]*" %>
    </div>
    </div>
<br>
    <div class="row">  
      <div class="col-4">
        <%= form.label :main_picture %>
        <%= form.file_field :main_picture, class: "form-control", required: true %>
    </div>
    </div>
<br>
    <div class="row">  
      <div class="col-4">
        <%= form.label :pictures %>
        <%= form.file_field :pictures, class: "form-control", multiple: true %>
    </div>
    </div>
<br>

    <div class="row">  
      <div class="col-4">
        <%= form.label :category %>
        
        <% options = options_from_collection_for_select(@categories, 'id', 'name') %>
        <%= form.select :category_id, options,  class: "form-control btn btn-secondary dropdown-toggle" %>
        </div>
    </div>
    <br>
    <%= form.submit class: "btn btn-primary " %>
<% end %>
<div>

app/views/admin/products/show.html.erb
<div class="container"> 

    <div class= "btn btn-warning">
        <h1><%= link_to "Edit", edit_admin_product_path(@product) %></h1>
    </div>
    <% if @product.main_picture  %>
      <% if @product.main_picture.representable? %>
        <p>Main Picture: </p> 

        <%= image_tag @product.main_picture %>   
    <% end %>
    <% end %>
<br>
        <p>Other Pictures:</p> 

  <% @product.pictures.each do |file| %>

      <% if file.representable? %>
        <%= image_tag file  %>
      <% else %>
        <%= link_to rails_blob_path(file, disposition: "attachment") do %>
          <%= image_tag "placeholder.png", alt: "Download file" %>
        <% end %>
      <% end %>
  <% end %>
<br>
<h1> Product Details </h1> 
<br>
<p><strong>Name : </strong>
<%=  @product.name %>
</p>

<p><strong>Brand : </strong>
<%= @product.brand %>
</p>

<p><strong>Price : </strong>

<%=   @product.price %>
<br>
</p>

<p><strong>Description : </strong>

<%=  @product.description %>
<br>
</p>

<p><strong>Category : </strong>

<%= @product.category.name %>
<br>
</p>

<p><strong>Weight : </strong>

<%=  @product.weight %>
<br>
</p>

</div>